name: Build Linux Sensor Driver

on:
  push:
    branches: [ main, master ]
    paths: [ 'driver/**' ]
  pull_request:
    branches: [ main, master ]
    paths: [ 'driver/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential linux-headers-$(uname -r) kmod sparse clang-format

      - name: Check code formatting
        run: clang-format -n -Werror driver/sensor_driver.c

      - name: Build driver module
        run: make -C driver

      - name: Static code analysis
        run: make -C driver C=2

      - name: Test driver module
        run: |
          cd driver
          cat > test_module.sh << 'EOF'
          #!/bin/bash
          set -e
          sudo insmod sensor_driver.ko
          lsmod | grep sensor_driver > /dev/null
          [[ -f /proc/my_dummy_sensor ]] && cat /proc/my_dummy_sensor
          sudo rmmod sensor_driver
          echo "All tests passed!"
          EOF
          chmod +x test_module.sh

          if [[ -f /proc/version && "$CI" == "true" ]]; then
            ./test_module.sh
          else
            echo "Skipping kernel module test outside CI with kernel access"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sensor-driver
          path: driver/sensor_driver.ko
